export const allProduct = [
  {
    id: 1,
    name: "Bàn phím cơ SteelSeries Apex Pro",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_06.jpg",
    orginalPrice: "3.500.000đ",
    discountPercent: "-8%",
    currentPrice: "3.220.000đ",
    price: 3220000,
    priceDiscountText: "Giảm 280.000đ",
    link: "./product-details.html?id=1",
    quantity: 100,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 2,
    name: "Bàn phím cơ Leopold FC750R",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_12.webp",
    orginalPrice: "2.300.000đ",
    discountPercent: "-13%",
    currentPrice: "2.001.000đ",
    price: 2001000,
    priceDiscountText: "Giảm 299.000đ",
    link: "./product-details.html?id=2",
    quantity: 11,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 3,
    name: "Bàn phím cơ Corsair K95 RGB Platinum",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_04.png",
    orginalPrice: "3.200.000đ",
    discountPercent: "-10%",
    currentPrice: "2.880.000đ",
    price: 2880000,
    priceDiscountText: "Giảm 320.000đ",
    link: "./product-details.html?id=3",
    quantity: 79,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 4,
    name: "Bàn phím cơ Razer BlackWidow V3",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_05.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-12%",
    currentPrice: "2.464.000đ",
    price: 2464000,
    priceDiscountText: "Giảm 336.000đ",
    link: "./product-details.html?id=4",
    quantity: 58,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 5,
    name: "Bàn phím cơ không dây AULA F75",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_02.png",
    orginalPrice: "1.000.000đ",
    discountPercent: "-20%",
    currentPrice: "800.000đ",
    price: 800000,
    priceDiscountText: "Giảm 200.000đ",
    link: "./product-details.html?id=5",
    quantity: 38,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 6,
    name: "Bàn phím cơ HyperX Alloy Elite 2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_07.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=6",
    quantity: 26,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 7,
    name: "Bàn phím cơ ASUS ROG Strix Scope",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_08.jpeg",
    orginalPrice: "2.600.000đ",
    discountPercent: "-14%",
    currentPrice: "2.236.000đ",
    price: 2236000,
    priceDiscountText: "Giảm 364.000đ",
    link: "./product-details.html?id=7",
    quantity: 97,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 8,
    name: "Bàn phím cơ Cooler Master CK550",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_09.webp",
    orginalPrice: "1.800.000đ",
    discountPercent: "-22%",
    currentPrice: "1.404.000đ",
    price: 1404000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=8",
    quantity: 90,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 9,
    name: "Bàn phím cơ Ducky One 3",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_10.webp",
    orginalPrice: "2.400.000đ",
    discountPercent: "-16%",
    currentPrice: "2.016.000đ",
    price: 2016000,
    priceDiscountText: "Giảm 384.000đ",
    link: "./product-details.html?id=9",
    quantity: 32,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 10,
    name: "Bàn phím cơ Varmilo VA87M",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_11.webp",
    orginalPrice: "2.100.000đ",
    discountPercent: "-20%",
    currentPrice: "1.680.000đ",
    price: 1680000,
    priceDiscountText: "Giảm 420.000đ",
    link: "./product-details.html?id=10",
    quantity: 37,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 11,
    name: "Bàn phím cơ Logitech G Pro X",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_03.png",
    orginalPrice: "2.500.000đ",
    discountPercent: "-15%",
    currentPrice: "2.125.000đ",
    price: 2125000,
    priceDiscountText: "Giảm 375.000đ",
    link: "./product-details.html?id=11",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 12,
    name: "Bàn phím cơ Filco Majestouch 2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_13.webp",
    orginalPrice: "2.700.000đ",
    discountPercent: "-11%",
    currentPrice: "2.403.000đ",
    price: 2403000,
    priceDiscountText: "Giảm 297.000đ",
    link: "./product-details.html?id=12",
    quantity: 15,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 13,
    name: "Bàn phím cơ Keychron K8",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_14.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-25%",
    currentPrice: "1.125.000đ",
    price: 1125000,
    priceDiscountText: "Giảm 375.000đ",
    link: "./product-details.html?id=13",
    quantity: 65,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 14,
    name: "Bàn phím cơ Anne Pro 2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_15.webp",
    orginalPrice: "1.600.000đ",
    discountPercent: "-19%",
    currentPrice: "1.296.000đ",
    price: 1296000,
    priceDiscountText: "Giảm 304.000đ",
    link: "./product-details.html?id=14",
    quantity: 46,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 15,
    name: "Bàn phím cơ RK61",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_16.webp",
    orginalPrice: "1.200.000đ",
    discountPercent: "-30%",
    currentPrice: "840.000đ",
    price: 840000,
    priceDiscountText: "Giảm 360.000đ",
    link: "./product-details.html?id=15",
    quantity: 82,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 16,
    name: "Bàn phím cơ GMMK Pro",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_17.webp",
    orginalPrice: "2.800.000đ",
    discountPercent: "-17%",
    currentPrice: "2.324.000đ",
    price: 2324000,
    priceDiscountText: "Giảm 476.000đ",
    link: "./product-details.html?id=16",
    quantity: 97,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 17,
    name: "Bàn phím cơ Drop ALT",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_18.jpg",
    orginalPrice: "3.000.000đ",
    discountPercent: "-9%",
    currentPrice: "2.730.000đ",
    price: 2730000,
    priceDiscountText: "Giảm 270.000đ",
    link: "./product-details.html?id=17",
    quantity: 58,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 18,
    name: "Bàn phím cơ Massdrop Ctrl",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_19.jpg",
    orginalPrice: "2.900.000đ",
    discountPercent: "-15%",
    currentPrice: "2.465.000đ",
    price: 2465000,
    priceDiscountText: "Giảm 435.000đ",
    link: "./product-details.html?id=18",
    quantity: 97,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 19,
    name: "Bàn phím cơ Vortex Race 3",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_20.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-21%",
    currentPrice: "1.738.000đ",
    price: 1738000,
    priceDiscountText: "Giảm 462.000đ",
    link: "./product-details.html?id=19",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 20,
    name: "Bàn phím cơ KBDfans KBD75",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_21.jpg",
    orginalPrice: "2.500.000đ",
    discountPercent: "-18%",
    currentPrice: "2.050.000đ",
    price: 2050000,
    priceDiscountText: "Giảm 450.000đ",
    link: "./product-details.html?id=20",
    quantity: 66,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 21,
    name: "Bàn phím cơ Tofu65",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_22.jpg",
    orginalPrice: "2.600.000đ",
    discountPercent: "-16%",
    currentPrice: "2.184.000đ",
    price: 2184000,
    priceDiscountText: "Giảm 416.000đ",
    link: "./product-details.html?id=21",
    quantity: 57,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 22,
    name: "Bàn phím cơ NK65 Entry Edition",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_23.jpg",
    orginalPrice: "2.300.000đ",
    discountPercent: "-23%",
    currentPrice: "1.771.000đ",
    price: 1771000,
    priceDiscountText: "Giảm 529.000đ",
    link: "./product-details.html?id=22",
    quantity: 17,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 23,
    name: "Bàn phím cơ Rama M65-B",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_24.webp",
    orginalPrice: "4.500.000đ",
    discountPercent: "-7%",
    currentPrice: "4.185.000đ",
    price: 4185000,
    priceDiscountText: "Giảm 315.000đ",
    link: "./product-details.html?id=23",
    quantity: 6,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 24,
    name: "Bàn phím cơ Satisfaction75",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_25.jpg",
    orginalPrice: "5.200.000đ",
    discountPercent: "-5%",
    currentPrice: "4.940.000đ",
    price: 4940000,
    priceDiscountText: "Giảm 260.000đ",
    link: "./product-details.html?id=24",
    quantity: 55,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 25,
    name: "Bàn phím cơ Think6.5 V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_26.webp",
    orginalPrice: "3.800.000đ",
    discountPercent: "-12%",
    currentPrice: "3.344.000đ",
    price: 3344000,
    priceDiscountText: "Giảm 456.000đ",
    link: "./product-details.html?id=25",
    quantity: 59,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 26,
    name: "Bàn phím cơ Space65",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_27.jpg",
    orginalPrice: "4.200.000đ",
    discountPercent: "-10%",
    currentPrice: "3.780.000đ",
    price: 3780000,
    priceDiscountText: "Giảm 420.000đ",
    link: "./product-details.html?id=26",
    quantity: 72,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 27,
    name: "Bàn phím cơ Polaris",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_28.webp",
    orginalPrice: "3.500.000đ",
    discountPercent: "-14%",
    currentPrice: "3.010.000đ",
    price: 3010000,
    priceDiscountText: "Giảm 490.000đ",
    link: "./product-details.html?id=27",
    quantity: 41,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 28,
    name: "Bàn phím cơ Vega",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_29.png",
    orginalPrice: "4.000.000đ",
    discountPercent: "-8%",
    currentPrice: "3.680.000đ",
    price: 3680000,
    priceDiscountText: "Giảm 320.000đ",
    link: "./product-details.html?id=28",
    quantity: 75,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 29,
    name: "Bàn phím cơ Iron165",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_30.png",
    orginalPrice: "3.600.000đ",
    discountPercent: "-11%",
    currentPrice: "3.204.000đ",
    price: 3204000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=29",
    quantity: 65,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 30,
    name: "Bàn phím cơ Bauer",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_31.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-13%",
    currentPrice: "2.784.000đ",
    price: 2784000,
    priceDiscountText: "Giảm 416.000đ",
    link: "./product-details.html?id=30",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 31,
    name: "Bàn phím cơ Matrix 2.0 Add",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_32.jpg",
    orginalPrice: "4.800.000đ",
    discountPercent: "-6%",
    currentPrice: "4.512.000đ",
    price: 4512000,
    priceDiscountText: "Giảm 288.000đ",
    link: "./product-details.html?id=31",
    quantity: 92,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 32,
    name: "Bàn phím cơ TGR Alice",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_33.jpg",
    orginalPrice: "5.500.000đ",
    discountPercent: "-4%",
    currentPrice: "5.280.000đ",
    price: 5280000,
    priceDiscountText: "Giảm 220.000đ",
    link: "./product-details.html?id=32",
    quantity: 77,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 33,
    name: "Bàn phím cơ Keycult No.1 Rev.1",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_34.jpg",
    orginalPrice: "6.200.000đ",
    discountPercent: "-3%",
    currentPrice: "6.014.000đ",
    price: 6014000,
    priceDiscountText: "Giảm 186.000đ",
    link: "./product-details.html?id=33",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 34,
    name: "Bàn phím cơ Duck Viper V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_35.jpg",
    orginalPrice: "4.500.000đ",
    discountPercent: "-9%",
    currentPrice: "4.095.000đ",
    price: 4095000,
    priceDiscountText: "Giảm 405.000đ",
    link: "./product-details.html?id=34",
    quantity: 61,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 35,
    name: "Bàn phím cơ Duck Eagle V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_36.jpg",
    orginalPrice: "4.200.000đ",
    discountPercent: "-12%",
    currentPrice: "3.696.000đ",
    price: 3696000,
    priceDiscountText: "Giảm 504.000đ",
    link: "./product-details.html?id=35",
    quantity: 3,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 36,
    name: "Bàn phím cơ Duck Lightsaver V3",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_37.jpg",
    orginalPrice: "4.800.000đ",
    discountPercent: "-8%",
    currentPrice: "4.416.000đ",
    price: 4416000,
    priceDiscountText: "Giảm 384.000đ",
    link: "./product-details.html?id=36",
    quantity: 64,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 37,
    name: "Bàn phím cơ Duck Orion V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_38.png",
    orginalPrice: "3.900.000đ",
    discountPercent: "-15%",
    currentPrice: "3.315.000đ",
    price: 3315000,
    priceDiscountText: "Giảm 585.000đ",
    link: "./product-details.html?id=37",
    quantity: 98,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 38,
    name: "Bàn phím cơ Duck Octagon V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_39.jpg",
    orginalPrice: "4.100.000đ",
    discountPercent: "-11%",
    currentPrice: "3.649.000đ",
    price: 3649000,
    priceDiscountText: "Giảm 451.000đ",
    link: "./product-details.html?id=38",
    quantity: 80,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 39,
    name: "Bàn phím cơ Duck Jetfire",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_40.webp",
    orginalPrice: "3.700.000đ",
    discountPercent: "-14%",
    currentPrice: "3.182.000đ",
    price: 3182000,
    priceDiscountText: "Giảm 518.000đ",
    link: "./product-details.html?id=39",
    quantity: 49,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 40,
    name: "Bàn phím cơ Duck Blackbird",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_41.webp",
    orginalPrice: "4.300.000đ",
    discountPercent: "-10%",
    currentPrice: "3.870.000đ",
    price: 3870000,
    priceDiscountText: "Giảm 430.000đ",
    link: "./product-details.html?id=40",
    quantity: 32,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 41,
    name: "Bàn phím cơ Duck Mini V2",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_42.webp",
    orginalPrice: "3.500.000đ",
    discountPercent: "-16%",
    currentPrice: "2.940.000đ",
    price: 2940000,
    priceDiscountText: "Giảm 560.000đ",
    link: "./product-details.html?id=41",
    quantity: 25,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 42,
    name: "Bàn phím cơ Duck Poker II",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_43.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-20%",
    currentPrice: "2.240.000đ",
    price: 2240000,
    priceDiscountText: "Giảm 560.000đ",
    link: "./product-details.html?id=42",
    quantity: 98,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 43,
    name: "Bàn phím cơ Duck Shine 3",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_44.webp",
    orginalPrice: "2.600.000đ",
    discountPercent: "-18%",
    currentPrice: "2.132.000đ",
    price: 2132000,
    priceDiscountText: "Giảm 468.000đ",
    link: "./product-details.html?id=43",
    quantity: 36,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 44,
    name: "Bàn phím cơ Duck Shine 4",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_45.png",
    orginalPrice: "2.900.000đ",
    discountPercent: "-17%",
    currentPrice: "2.407.000đ",
    price: 2407000,
    priceDiscountText: "Giảm 493.000đ",
    link: "./product-details.html?id=44",
    quantity: 28,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 45,
    name: "Bàn phím cơ Duck Shine 5",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_46.png",
    orginalPrice: "3.100.000đ",
    discountPercent: "-15%",
    currentPrice: "2.635.000đ",
    price: 2635000,
    priceDiscountText: "Giảm 465.000đ",
    link: "./product-details.html?id=45",
    quantity: 49,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 46,
    name: "Bàn phím cơ Duck Shine 6",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_47.webp",
    orginalPrice: "3.300.000đ",
    discountPercent: "-13%",
    currentPrice: "2.871.000đ",
    price: 2871000,
    priceDiscountText: "Giảm 429.000đ",
    link: "./product-details.html?id=46",
    quantity: 21,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 47,
    name: "Bàn phím cơ Duck Shine 7",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_48.webp",
    orginalPrice: "3.500.000đ",
    discountPercent: "-12%",
    currentPrice: "3.080.000đ",
    price: 3080000,
    priceDiscountText: "Giảm 420.000đ",
    link: "./product-details.html?id=47",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 48,
    name: "Bàn phím cơ Duck Shine 8",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_49.webp",
    orginalPrice: "3.700.000đ",
    discountPercent: "-11%",
    currentPrice: "3.293.000đ",
    price: 3293000,
    priceDiscountText: "Giảm 407.000đ",
    link: "./product-details.html?id=48",
    quantity: 35,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 49,
    name: "Bàn phím cơ Duck Shine 9",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_50.webp",
    orginalPrice: "3.900.000đ",
    discountPercent: "-10%",
    currentPrice: "3.510.000đ",
    price: 3510000,
    priceDiscountText: "Giảm 390.000đ",
    link: "./product-details.html?id=49",
    quantity: 35,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 50,
    name: "Bàn phím cơ Duck Shine 10",
    category: "keyboard",
    imgSrc: "./assets/img/Keyboard/keyboard_01.jpg",
    orginalPrice: "4.100.000đ",
    discountPercent: "-9%",
    currentPrice: "3.731.000đ",
    price: 3731000,
    priceDiscountText: "Giảm 369.000đ",
    link: "./product-details.html?id=50",
    quantity: 21,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 51,
    name: "Chuột gaming Logitech G Pro X Superlight",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_01.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-15%",
    currentPrice: "1.870.000đ",
    price: 1870000,
    priceDiscountText: "Giảm 330.000đ",
    link: "./product-details.html?id=51",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 52,
    name: "Chuột gaming Razer DeathAdder V3 Pro",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_02.jpg",
    orginalPrice: "2.500.000đ",
    discountPercent: "-12%",
    currentPrice: "2.200.000đ",
    price: 2200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=52",
    quantity: 21,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 53,
    name: "Chuột gaming SteelSeries Aerox 3",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_03.png",
    orginalPrice: "1.800.000đ",
    discountPercent: "-18%",
    currentPrice: "1.476.000đ",
    price: 1476000,
    priceDiscountText: "Giảm 324.000đ",
    link: "./product-details.html?id=53",
    quantity: 73,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 54,
    name: "Chuột gaming Corsair Dark Core RGB Pro",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_04.jpg",
    orginalPrice: "2.100.000đ",
    discountPercent: "-14%",
    currentPrice: "1.806.000đ",
    price: 1806000,
    priceDiscountText: "Giảm 294.000đ",
    link: "./product-details.html?id=54",
    quantity: 18,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 55,
    name: "Chuột gaming HyperX Pulsefire Haste",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_05.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=55",
    quantity: 75,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 56,
    name: "Chuột gaming ASUS ROG Gladius III",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_06.webp",
    orginalPrice: "1.900.000đ",
    discountPercent: "-16%",
    currentPrice: "1.596.000đ",
    price: 1596000,
    priceDiscountText: "Giảm 304.000đ",
    link: "./product-details.html?id=56",
    quantity: 2,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 57,
    name: "Chuột gaming Cooler Master MM711",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_07.jpg",
    orginalPrice: "1.200.000đ",
    discountPercent: "-25%",
    currentPrice: "900.000đ",
    price: 900000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=57",
    quantity: 1,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 58,
    name: "Chuột gaming Zowie EC2-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_08.jpg",
    orginalPrice: "1.600.000đ",
    discountPercent: "-19%",
    currentPrice: "1.296.000đ",
    price: 1296000,
    priceDiscountText: "Giảm 304.000đ",
    link: "./product-details.html?id=58",
    quantity: 35,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 59,
    name: "Chuột gaming Finalmouse Starlight-12",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_09.jpg",
    orginalPrice: "3.500.000đ",
    discountPercent: "-8%",
    currentPrice: "3.220.000đ",
    price: 3220000,
    priceDiscountText: "Giảm 280.000đ",
    link: "./product-details.html?id=59",
    quantity: 36,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 60,
    name: "Chuột gaming Glorious Model O",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_10.jpg",
    orginalPrice: "1.400.000đ",
    discountPercent: "-22%",
    currentPrice: "1.092.000đ",
    price: 1092000,
    priceDiscountText: "Giảm 308.000đ",
    link: "./product-details.html?id=60",
    quantity: 25,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 61,
    name: "Chuột gaming Glorious Model D",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_11.jpg",
    orginalPrice: "1.400.000đ",
    discountPercent: "-21%",
    currentPrice: "1.106.000đ",
    price: 1106000,
    priceDiscountText: "Giảm 294.000đ",
    link: "./product-details.html?id=61",
    quantity: 5,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 62,
    name: "Chuột gaming Pulsar Xlite V2",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_12.jpg",
    orginalPrice: "1.800.000đ",
    discountPercent: "-17%",
    currentPrice: "1.494.000đ",
    price: 1494000,
    priceDiscountText: "Giảm 306.000đ",
    link: "./product-details.html?id=62",
    quantity: 32,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 63,
    name: "Chuột gaming Ninjutso OOX",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_13.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-13%",
    currentPrice: "1.914.000đ",
    price: 1914000,
    priceDiscountText: "Giảm 286.000đ",
    link: "./product-details.html?id=63",
    quantity: 59,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 64,
    name: "Chuột gaming Xtrfy M42",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_14.webp",
    orginalPrice: "1.600.000đ",
    discountPercent: "-20%",
    currentPrice: "1.280.000đ",
    price: 1280000,
    priceDiscountText: "Giảm 320.000đ",
    link: "./product-details.html?id=64",
    quantity: 81,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 65,
    name: "Chuột gaming Xtrfy M4",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_15.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-23%",
    currentPrice: "1.155.000đ",
    price: 1155000,
    priceDiscountText: "Giảm 345.000đ",
    link: "./product-details.html?id=65",
    quantity: 20,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 66,
    name: "Chuột gaming Endgame Gear XM1R",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_16.jpg",
    orginalPrice: "1.700.000đ",
    discountPercent: "-18%",
    currentPrice: "1.394.000đ",
    price: 1394000,
    priceDiscountText: "Giảm 306.000đ",
    link: "./product-details.html?id=66",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 67,
    name: "Chuột gaming Vaxee Outset AX",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_17.png",
    orginalPrice: "1.800.000đ",
    discountPercent: "-16%",
    currentPrice: "1.512.000đ",
    price: 1512000,
    priceDiscountText: "Giảm 288.000đ",
    link: "./product-details.html?id=67",
    quantity: 69,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 68,
    name: "Chuột gaming Vaxee NP-01",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_18.jpg",
    orginalPrice: "1.600.000đ",
    discountPercent: "-19%",
    currentPrice: "1.296.000đ",
    price: 1296000,
    priceDiscountText: "Giảm 304.000đ",
    link: "./product-details.html?id=68",
    quantity: 10,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 69,
    name: "Chuột gaming Vaxee Zygen NP-01S",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_19.png",
    orginalPrice: "1.700.000đ",
    discountPercent: "-17%",
    currentPrice: "1.411.000đ",
    price: 1411000,
    priceDiscountText: "Giảm 289.000đ",
    link: "./product-details.html?id=69",
    quantity: 38,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 70,
    name: "Chuột gaming Roccat Kone Pro Air",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_20.jpg",
    orginalPrice: "2.000.000đ",
    discountPercent: "-15%",
    currentPrice: "1.700.000đ",
    price: 1700000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=70",
    quantity: 15,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 71,
    name: "Chuột gaming Roccat Burst Pro",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_21.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-24%",
    currentPrice: "1.140.000đ",
    price: 1140000,
    priceDiscountText: "Giảm 360.000đ",
    link: "./product-details.html?id=71",
    quantity: 39,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 72,
    name: "Chuột gaming Roccat Kain 120",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_22.webp",
    orginalPrice: "1.400.000đ",
    discountPercent: "-21%",
    currentPrice: "1.106.000đ",
    price: 1106000,
    priceDiscountText: "Giảm 294.000đ",
    link: "./product-details.html?id=72",
    quantity: 65,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 73,
    name: "Chuột gaming BenQ Zowie FK1-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_23.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=73",
    quantity: 18,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 74,
    name: "Chuột gaming BenQ Zowie FK2-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_24.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=74",
    quantity: 68,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 75,
    name: "Chuột gaming BenQ Zowie S1-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_25.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=75",
    quantity: 87,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 76,
    name: "Chuột gaming BenQ Zowie S2-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_26.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=76",
    quantity: 11,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 77,
    name: "Chuột gaming BenQ Zowie ZA11-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_27.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=77",
    quantity: 29,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 78,
    name: "Chuột gaming BenQ Zowie ZA12-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_28.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=78",
    quantity: 46,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 79,
    name: "Chuột gaming BenQ Zowie ZA13-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_29.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=79",
    quantity: 57,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 80,
    name: "Chuột gaming BenQ Zowie EC1-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_30.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=80",
    quantity: 69,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 81,
    name: "Chuột gaming BenQ Zowie EC3-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_31.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=81",
    quantity: 90,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 82,
    name: "Chuột gaming BenQ Zowie FK1+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_32.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=82",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 83,
    name: "Chuột gaming BenQ Zowie FK2+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_33.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=83",
    quantity: 99,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 84,
    name: "Chuột gaming BenQ Zowie S1+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_34.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=84",
    quantity: 97,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 85,
    name: "Chuột gaming BenQ Zowie S2+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_35.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=85",
    quantity: 67,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 86,
    name: "Chuột gaming BenQ Zowie ZA11+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_36.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=86",
    quantity: 56,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 87,
    name: "Chuột gaming BenQ Zowie ZA12+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_37.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=87",
    quantity: 96,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 88,
    name: "Chuột gaming BenQ Zowie ZA13+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_38.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=88",
    quantity: 86,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 89,
    name: "Chuột gaming BenQ Zowie EC1+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_39.webp",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=89",
    quantity: 9,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 90,
    name: "Chuột gaming BenQ Zowie EC3+-C",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_40.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=90",
    quantity: 71,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 91,
    name: "Chuột gaming BenQ Zowie FK1-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_41.webp",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=91",
    quantity: 56,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 92,
    name: "Chuột gaming BenQ Zowie FK2-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_42.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=92",
    quantity: 7,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 93,
    name: "Chuột gaming BenQ Zowie S1-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_43.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=93",
    quantity: 65,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 94,
    name: "Chuột gaming BenQ Zowie S2-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_44.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=94",
    quantity: 69,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 95,
    name: "Chuột gaming BenQ Zowie ZA11-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_45.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=95",
    quantity: 55,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 96,
    name: "Chuột gaming BenQ Zowie ZA12-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_46.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=96",
    quantity: 69,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 97,
    name: "Chuột gaming BenQ Zowie ZA13-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_47.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=97",
    quantity: 38,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 98,
    name: "Chuột gaming BenQ Zowie EC1-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_48.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=98",
    quantity: 96,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 99,
    name: "Chuột gaming BenQ Zowie EC3-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_49.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=99",
    quantity: 58,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 100,
    name: "Chuột gaming BenQ Zowie EC2-CW",
    category: "mouse",
    imgSrc: "./assets/img/Mouse/mouse_50.png",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=100",
    quantity: 10,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 101,
    name: "Tai nghe gaming Logitech G Pro X",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_01.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-15%",
    currentPrice: "2.380.000đ",
    price: 2380000,
    priceDiscountText: "Giảm 420.000đ",
    link: "./product-details.html?id=101",
    quantity: 95,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 102,
    name: "Tai nghe gaming Razer BlackShark V2 Pro",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_02.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-12%",
    currentPrice: "2.816.000đ",
    price: 2816000,
    priceDiscountText: "Giảm 384.000đ",
    link: "./product-details.html?id=102",
    quantity: 41,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 103,
    name: "Tai nghe gaming SteelSeries Arctis Pro",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_03.jpg",
    orginalPrice: "4.500.000đ",
    discountPercent: "-10%",
    currentPrice: "4.050.000đ",
    price: 4050000,
    priceDiscountText: "Giảm 450.000đ",
    link: "./product-details.html?id=103",
    quantity: 65,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 104,
    name: "Tai nghe gaming Corsair Virtuoso RGB Wireless",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_04.jpg",
    orginalPrice: "3.800.000đ",
    discountPercent: "-14%",
    currentPrice: "3.268.000đ",
    price: 3268000,
    priceDiscountText: "Giảm 532.000đ",
    link: "./product-details.html?id=104",
    quantity: 5,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 105,
    name: "Tai nghe gaming HyperX Cloud Alpha S",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_05.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-18%",
    currentPrice: "1.804.000đ",
    price: 1804000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=105",
    quantity: 49,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 106,
    name: "Tai nghe gaming ASUS ROG Delta S",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_06.jpg",
    orginalPrice: "2.600.000đ",
    discountPercent: "-16%",
    currentPrice: "2.184.000đ",
    price: 2184000,
    priceDiscountText: "Giảm 416.000đ",
    link: "./product-details.html?id=106",
    quantity: 56,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 107,
    name: "Tai nghe gaming Cooler Master MH751",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_07.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-20%",
    currentPrice: "1.200.000đ",
    price: 1200000,
    priceDiscountText: "Giảm 300.000đ",
    link: "./product-details.html?id=107",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 108,
    name: "Tai nghe gaming Sennheiser GSP 600",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_08.jpg",
    orginalPrice: "3.500.000đ",
    discountPercent: "-13%",
    currentPrice: "3.045.000đ",
    price: 3045000,
    priceDiscountText: "Giảm 455.000đ",
    link: "./product-details.html?id=108",
    quantity: 16,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 109,
    name: "Tai nghe gaming Audio-Technica ATH-G1",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_09.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-17%",
    currentPrice: "2.324.000đ",
    price: 2324000,
    priceDiscountText: "Giảm 476.000đ",
    link: "./product-details.html?id=109",
    quantity: 93,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 110,
    name: "Tai nghe gaming Beyerdynamic DT 990",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_10.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-11%",
    currentPrice: "2.848.000đ",
    price: 2848000,
    priceDiscountText: "Giảm 352.000đ",
    link: "./product-details.html?id=110",
    quantity: 41,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 111,
    name: "Tai nghe gaming Beyerdynamic DT 770",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_11.jpg",
    orginalPrice: "2.900.000đ",
    discountPercent: "-15%",
    currentPrice: "2.465.000đ",
    price: 2465000,
    priceDiscountText: "Giảm 435.000đ",
    link: "./product-details.html?id=111",
    quantity: 31,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 112,
    name: "Tai nghe gaming Beyerdynamic DT 880",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_12.jpg",
    orginalPrice: "3.000.000đ",
    discountPercent: "-14%",
    currentPrice: "2.580.000đ",
    price: 2580000,
    priceDiscountText: "Giảm 420.000đ",
    link: "./product-details.html?id=112",
    quantity: 53,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 113,
    name: "Tai nghe gaming AKG K702",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_13.jpg",
    orginalPrice: "2.700.000đ",
    discountPercent: "-19%",
    currentPrice: "2.187.000đ",
    price: 2187000,
    priceDiscountText: "Giảm 513.000đ",
    link: "./product-details.html?id=113",
    quantity: 55,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 114,
    name: "Tai nghe gaming AKG K612 Pro",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_14.jpg",
    orginalPrice: "2.400.000đ",
    discountPercent: "-21%",
    currentPrice: "1.896.000đ",
    price: 1896000,
    priceDiscountText: "Giảm 504.000đ",
    link: "./product-details.html?id=114",
    quantity: 45,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 115,
    name: "Tai nghe gaming AKG K712 Pro",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_15.jpg",
    orginalPrice: "3.100.000đ",
    discountPercent: "-16%",
    currentPrice: "2.604.000đ",
    price: 2604000,
    priceDiscountText: "Giảm 496.000đ",
    link: "./product-details.html?id=115",
    quantity: 29,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 116,
    name: "Tai nghe gaming Philips Fidelio X2HR",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_16.jpg",
    orginalPrice: "2.500.000đ",
    discountPercent: "-18%",
    currentPrice: "2.050.000đ",
    price: 2050000,
    priceDiscountText: "Giảm 450.000đ",
    link: "./product-details.html?id=116",
    quantity: 76,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 117,
    name: "Tai nghe gaming Philips SHP9500",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_17.jpg",
    orginalPrice: "1.800.000đ",
    discountPercent: "-22%",
    currentPrice: "1.404.000đ",
    price: 1404000,
    priceDiscountText: "Giảm 396.000đ",
    link: "./product-details.html?id=117",
    quantity: 64,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 118,
    name: "Tai nghe gaming Philips Fidelio L2",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_18.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-20%",
    currentPrice: "1.760.000đ",
    price: 1760000,
    priceDiscountText: "Giảm 440.000đ",
    link: "./product-details.html?id=118",
    quantity: 95,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 119,
    name: "Tai nghe gaming Philips Fidelio X1",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_19.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-17%",
    currentPrice: "2.324.000đ",
    price: 2324000,
    priceDiscountText: "Giảm 476.000đ",
    link: "./product-details.html?id=119",
    quantity: 33,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 120,
    name: "Tai nghe gaming Philips Fidelio X3",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_20.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-15%",
    currentPrice: "2.720.000đ",
    price: 2720000,
    priceDiscountText: "Giảm 480.000đ",
    link: "./product-details.html?id=120",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 121,
    name: "Tai nghe gaming Hifiman Sundara",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_21.jpg",
    orginalPrice: "4.200.000đ",
    discountPercent: "-12%",
    currentPrice: "3.696.000đ",
    price: 3696000,
    priceDiscountText: "Giảm 504.000đ",
    link: "./product-details.html?id=121",
    quantity: 43,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 122,
    name: "Tai nghe gaming Hifiman HE400se",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_22.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-18%",
    currentPrice: "2.296.000đ",
    price: 2296000,
    priceDiscountText: "Giảm 504.000đ",
    link: "./product-details.html?id=122",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 123,
    name: "Tai nghe gaming Hifiman HE560",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_23.jpg",
    orginalPrice: "5.500.000đ",
    discountPercent: "-9%",
    currentPrice: "5.005.000đ",
    price: 5005000,
    priceDiscountText: "Giảm 495.000đ",
    link: "./product-details.html?id=123",
    quantity: 29,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 124,
    name: "Tai nghe gaming Hifiman Ananda",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_24.jpg",
    orginalPrice: "8.500.000đ",
    discountPercent: "-7%",
    currentPrice: "7.905.000đ",
    price: 7905000,
    priceDiscountText: "Giảm 595.000đ",
    link: "./product-details.html?id=124",
    quantity: 49,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 125,
    name: "Tai nghe gaming Hifiman Arya",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_25.jpg",
    orginalPrice: "12.000.000đ",
    discountPercent: "-5%",
    currentPrice: "11.400.000đ",
    price: 11400000,
    priceDiscountText: "Giảm 600.000đ",
    link: "./product-details.html?id=125",
    quantity: 9,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 126,
    name: "Tai nghe gaming Focal Clear",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_26.jpg",
    orginalPrice: "15.000.000đ",
    discountPercent: "-4%",
    currentPrice: "14.400.000đ",
    price: 14400000,
    priceDiscountText: "Giảm 600.000đ",
    link: "./product-details.html?id=126",
    quantity: 73,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 127,
    name: "Tai nghe gaming Focal Utopia",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_27.jpg",
    orginalPrice: "45.000.000đ",
    discountPercent: "-2%",
    currentPrice: "44.100.000đ",
    price: 44100000,
    priceDiscountText: "Giảm 900.000đ",
    link: "./product-details.html?id=127",
    quantity: 14,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 128,
    name: "Tai nghe gaming Focal Stellia",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_28.jpg",
    orginalPrice: "35.000.000đ",
    discountPercent: "-3%",
    currentPrice: "33.950.000đ",
    price: 33950000,
    priceDiscountText: "Giảm 1.050.000đ",
    link: "./product-details.html?id=128",
    quantity: 9,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 129,
    name: "Tai nghe gaming Focal Elegia",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_29.jpg",
    orginalPrice: "8.500.000đ",
    discountPercent: "-8%",
    currentPrice: "7.820.000đ",
    price: 7820000,
    priceDiscountText: "Giảm 680.000đ",
    link: "./product-details.html?id=129",
    quantity: 74,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 130,
    name: "Tai nghe gaming Focal Radiance",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_30.jpg",
    orginalPrice: "12.000.000đ",
    discountPercent: "-6%",
    currentPrice: "11.280.000đ",
    price: 11280000,
    priceDiscountText: "Giảm 720.000đ",
    link: "./product-details.html?id=130",
    quantity: 67,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 131,
    name: "Tai nghe gaming Audeze LCD-2",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_31.jpg",
    orginalPrice: "18.000.000đ",
    discountPercent: "-5%",
    currentPrice: "17.100.000đ",
    price: 17100000,
    priceDiscountText: "Giảm 900.000đ",
    link: "./product-details.html?id=131",
    quantity: 1,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 132,
    name: "Tai nghe gaming Audeze LCD-3",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_32.jpg",
    orginalPrice: "28.000.000đ",
    discountPercent: "-4%",
    currentPrice: "26.880.000đ",
    price: 26880000,
    priceDiscountText: "Giảm 1.120.000đ",
    link: "./product-details.html?id=132",
    quantity: 91,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 133,
    name: "Tai nghe gaming Audeze LCD-4",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_33.jpg",
    orginalPrice: "45.000.000đ",
    discountPercent: "-3%",
    currentPrice: "43.650.000đ",
    price: 43650000,
    priceDiscountText: "Giảm 1.350.000đ",
    link: "./product-details.html?id=133",
    quantity: 92,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 134,
    name: "Tai nghe gaming Audeze LCD-X",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_34.jpg",
    orginalPrice: "22.000.000đ",
    discountPercent: "-6%",
    currentPrice: "20.680.000đ",
    price: 20680000,
    priceDiscountText: "Giảm 1.320.000đ",
    link: "./product-details.html?id=134",
    quantity: 71,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 135,
    name: "Tai nghe gaming Audeze LCD-1",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_35.jpg",
    orginalPrice: "8.500.000đ",
    discountPercent: "-9%",
    currentPrice: "7.735.000đ",
    price: 7735000,
    priceDiscountText: "Giảm 765.000đ",
    link: "./product-details.html?id=135",
    quantity: 38,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 136,
    name: "Tai nghe gaming Audeze LCD-GX",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_36.jpg",
    orginalPrice: "15.000.000đ",
    discountPercent: "-7%",
    currentPrice: "13.950.000đ",
    price: 13950000,
    priceDiscountText: "Giảm 1.050.000đ",
    link: "./product-details.html?id=136",
    quantity: 56,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 137,
    name: "Tai nghe gaming Audeze LCD-2C",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_37.jpg",
    orginalPrice: "16.000.000đ",
    discountPercent: "-8%",
    currentPrice: "14.720.000đ",
    price: 14720000,
    priceDiscountText: "Giảm 1.280.000đ",
    link: "./product-details.html?id=137",
    quantity: 52,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 138,
    name: "Tai nghe gaming Audeze LCD-3F",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_38.jpg",
    orginalPrice: "26.000.000đ",
    discountPercent: "-5%",
    currentPrice: "24.700.000đ",
    price: 24700000,
    priceDiscountText: "Giảm 1.300.000đ",
    link: "./product-details.html?id=138",
    quantity: 54,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 139,
    name: "Tai nghe gaming Audeze LCD-4Z",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_39.jpg",
    orginalPrice: "42.000.000đ",
    discountPercent: "-4%",
    currentPrice: "40.320.000đ",
    price: 40320000,
    priceDiscountText: "Giảm 1.680.000đ",
    link: "./product-details.html?id=139",
    quantity: 89,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 140,
    name: "Tai nghe gaming Audeze LCD-XC",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_40.jpg",
    orginalPrice: "20.000.000đ",
    discountPercent: "-6%",
    currentPrice: "18.800.000đ",
    price: 18800000,
    priceDiscountText: "Giảm 1.200.000đ",
    link: "./product-details.html?id=140",
    quantity: 42,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 141,
    name: "Tai nghe gaming Audeze LCD-2 Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_41.jpg",
    orginalPrice: "15.500.000đ",
    discountPercent: "-7%",
    currentPrice: "14.415.000đ",
    price: 14415000,
    priceDiscountText: "Giảm 1.085.000đ",
    link: "./product-details.html?id=141",
    quantity: 78,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 142,
    name: "Tai nghe gaming Audeze LCD-3 Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_42.jpg",
    orginalPrice: "25.000.000đ",
    discountPercent: "-5%",
    currentPrice: "23.750.000đ",
    price: 23750000,
    priceDiscountText: "Giảm 1.250.000đ",
    link: "./product-details.html?id=142",
    quantity: 29,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 143,
    name: "Tai nghe gaming Audeze LCD-4 Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_43.jpg",
    orginalPrice: "40.000.000đ",
    discountPercent: "-3%",
    currentPrice: "38.800.000đ",
    price: 38800000,
    priceDiscountText: "Giảm 1.200.000đ",
    link: "./product-details.html?id=143",
    quantity: 3,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 144,
    name: "Tai nghe gaming Audeze LCD-X Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_44.jpg",
    orginalPrice: "19.000.000đ",
    discountPercent: "-6%",
    currentPrice: "17.860.000đ",
    price: 17860000,
    priceDiscountText: "Giảm 1.140.000đ",
    link: "./product-details.html?id=144",
    quantity: 35,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 145,
    name: "Tai nghe gaming Audeze LCD-1 Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_45.jpg",
    orginalPrice: "7.500.000đ",
    discountPercent: "-9%",
    currentPrice: "6.825.000đ",
    price: 6825000,
    priceDiscountText: "Giảm 675.000đ",
    link: "./product-details.html?id=145",
    quantity: 87,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 146,
    name: "Tai nghe gaming Audeze LCD-GX Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_46.jpg",
    orginalPrice: "13.500.000đ",
    discountPercent: "-7%",
    currentPrice: "12.555.000đ",
    price: 12555000,
    priceDiscountText: "Giảm 945.000đ",
    link: "./product-details.html?id=146",
    quantity: 78,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 147,
    name: "Tai nghe gaming Audeze LCD-2C Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_47.jpg",
    orginalPrice: "14.000.000đ",
    discountPercent: "-8%",
    currentPrice: "12.880.000đ",
    price: 12880000,
    priceDiscountText: "Giảm 1.120.000đ",
    link: "./product-details.html?id=147",
    quantity: 42,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 148,
    name: "Tai nghe gaming Audeze LCD-3F Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_48.jpg",
    orginalPrice: "23.000.000đ",
    discountPercent: "-5%",
    currentPrice: "21.850.000đ",
    price: 21850000,
    priceDiscountText: "Giảm 1.150.000đ",
    link: "./product-details.html?id=148",
    quantity: 3,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 149,
    name: "Tai nghe gaming Audeze LCD-4Z Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_49.jpg",
    orginalPrice: "38.000.000đ",
    discountPercent: "-4%",
    currentPrice: "36.480.000đ",
    price: 36480000,
    priceDiscountText: "Giảm 1.520.000đ",
    link: "./product-details.html?id=149",
    quantity: 83,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 150,
    name: "Tai nghe gaming Audeze LCD-XC Classic",
    category: "headphone",
    imgSrc: "./assets/img/HEADPHONE/headphone_50.jpg",
    orginalPrice: "18.000.000đ",
    discountPercent: "-6%",
    currentPrice: "16.920.000đ",
    price: 16920000,
    priceDiscountText: "Giảm 1.080.000đ",
    link: "./product-details.html?id=150",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 151,
    name: "Sạc dự phòng Xiaomi Power Bank 20000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_01.jpg",
    orginalPrice: "800.000đ",
    discountPercent: "-15%",
    currentPrice: "680.000đ",
    price: 680000,
    priceDiscountText: "Giảm 120.000đ",
    link: "./product-details.html?id=151",
    quantity: 24,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 152,
    name: "Sạc dự phòng Anker PowerCore 10000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_02.jpg",
    orginalPrice: "600.000đ",
    discountPercent: "-20%",
    currentPrice: "480.000đ",
    price: 480000,
    priceDiscountText: "Giảm 120.000đ",
    link: "./product-details.html?id=152",
    quantity: 45,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 153,
    name: "Sạc dự phòng Samsung Wireless Power Bank 10000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_03.jpg",
    orginalPrice: "1.200.000đ",
    discountPercent: "-12%",
    currentPrice: "1.056.000đ",
    price: 1056000,
    priceDiscountText: "Giảm 144.000đ",
    link: "./product-details.html?id=153",
    quantity: 97,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 154,
    name: "Sạc dự phòng Romoss Sense 6 Plus 20000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_04.jpg",
    orginalPrice: "700.000đ",
    discountPercent: "-18%",
    currentPrice: "574.000đ",
    price: 574000,
    priceDiscountText: "Giảm 126.000đ",
    link: "./product-details.html?id=154",
    quantity: 62,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 155,
    name: "Sạc dự phòng Baseus Blade 10000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_05.jpg",
    orginalPrice: "500.000đ",
    discountPercent: "-22%",
    currentPrice: "390.000đ",
    price: 390000,
    priceDiscountText: "Giảm 110.000đ",
    link: "./product-details.html?id=155",
    quantity: 89,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 156,
    name: "Sạc dự phòng RavPower 20000mAh PD",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_06.jpg",
    orginalPrice: "900.000đ",
    discountPercent: "-16%",
    currentPrice: "756.000đ",
    price: 756000,
    priceDiscountText: "Giảm 144.000đ",
    link: "./product-details.html?id=156",
    quantity: 61,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 157,
    name: "Sạc dự phòng Mophie Powerstation Plus 10000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_07.jpg",
    orginalPrice: "1.500.000đ",
    discountPercent: "-14%",
    currentPrice: "1.290.000đ",
    price: 1290000,
    priceDiscountText: "Giảm 210.000đ",
    link: "./product-details.html?id=157",
    quantity: 14,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 158,
    name: "Sạc dự phòng Belkin Boost Charge 10000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_08.jpg",
    orginalPrice: "1.100.000đ",
    discountPercent: "-17%",
    currentPrice: "913.000đ",
    price: 913000,
    priceDiscountText: "Giảm 187.000đ",
    link: "./product-details.html?id=158",
    quantity: 66,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 159,
    name: "Sạc dự phòng Zendure SuperTank 27000mAh",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_09.jpg",
    orginalPrice: "2.500.000đ",
    discountPercent: "-10%",
    currentPrice: "2.250.000đ",
    price: 2250000,
    priceDiscountText: "Giảm 250.000đ",
    link: "./product-details.html?id=159",
    quantity: 25,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 160,
    name: "Sạc dự phòng Goal Zero Yeti 1000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_10.jpg",
    orginalPrice: "8.500.000đ",
    discountPercent: "-8%",
    currentPrice: "7.820.000đ",
    price: 7820000,
    priceDiscountText: "Giảm 680.000đ",
    link: "./product-details.html?id=160",
    quantity: 59,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 161,
    name: "Sạc dự phòng Jackery Explorer 240",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_11.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-13%",
    currentPrice: "2.784.000đ",
    price: 2784000,
    priceDiscountText: "Giảm 416.000đ",
    link: "./product-details.html?id=161",
    quantity: 87,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 162,
    name: "Sạc dự phòng EcoFlow River 600",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_12.jpg",
    orginalPrice: "5.500.000đ",
    discountPercent: "-11%",
    currentPrice: "4.895.000đ",
    price: 4895000,
    priceDiscountText: "Giảm 605.000đ",
    link: "./product-details.html?id=162",
    quantity: 11,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 163,
    name: "Sạc dự phòng Bluetti EB3A",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_13.jpg",
    orginalPrice: "4.200.000đ",
    discountPercent: "-15%",
    currentPrice: "3.570.000đ",
    price: 3570000,
    priceDiscountText: "Giảm 630.000đ",
    link: "./product-details.html?id=163",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 164,
    name: "Sạc dự phòng Renogy Phoenix 200",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_14.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-19%",
    currentPrice: "2.268.000đ",
    price: 2268000,
    priceDiscountText: "Giảm 532.000đ",
    link: "./product-details.html?id=164",
    quantity: 60,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 165,
    name: "Sạc dự phòng Rockpals 300W",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_15.jpg",
    orginalPrice: "3.500.000đ",
    discountPercent: "-16%",
    currentPrice: "2.940.000đ",
    price: 2940000,
    priceDiscountText: "Giảm 560.000đ",
    link: "./product-details.html?id=165",
    quantity: 84,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 166,
    name: "Sạc dự phòng Suaoki S270",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_16.jpg",
    orginalPrice: "2.200.000đ",
    discountPercent: "-21%",
    currentPrice: "1.738.000đ",
    price: 1738000,
    priceDiscountText: "Giảm 462.000đ",
    link: "./product-details.html?id=166",
    quantity: 20,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 167,
    name: "Sạc dự phòng Flashfish 300W",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_17.jpg",
    orginalPrice: "2.800.000đ",
    discountPercent: "-18%",
    currentPrice: "2.296.000đ",
    price: 2296000,
    priceDiscountText: "Giảm 504.000đ",
    link: "./product-details.html?id=167",
    quantity: 28,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 168,
    name: "Sạc dự phòng Westing iGen1200",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_18.jpg",
    orginalPrice: "4.500.000đ",
    discountPercent: "-14%",
    currentPrice: "3.870.000đ",
    price: 3870000,
    priceDiscountText: "Giảm 630.000đ",
    link: "./product-details.html?id=168",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 169,
    name: "Sạc dự phòng Champion 2000W",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_19.jpg",
    orginalPrice: "6.800.000đ",
    discountPercent: "-12%",
    currentPrice: "5.984.000đ",
    price: 5984000,
    priceDiscountText: "Giảm 816.000đ",
    link: "./product-details.html?id=169",
    quantity: 3,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 170,
    name: "Sạc dự phòng Generac GP3000i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_20.jpg",
    orginalPrice: "8.200.000đ",
    discountPercent: "-10%",
    currentPrice: "7.380.000đ",
    price: 7380000,
    priceDiscountText: "Giảm 820.000đ",
    link: "./product-details.html?id=170",
    quantity: 16,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 171,
    name: "Sạc dự phòng Honda EU2200i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_21.jpg",
    orginalPrice: "12.500.000đ",
    discountPercent: "-8%",
    currentPrice: "11.500.000đ",
    price: 11500000,
    priceDiscountText: "Giảm 1.000.000đ",
    link: "./product-details.html?id=171",
    quantity: 23,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 172,
    name: "Sạc dự phòng Yamaha EF2000iS",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_22.jpg",
    orginalPrice: "11.800.000đ",
    discountPercent: "-9%",
    currentPrice: "10.738.000đ",
    price: 10738000,
    priceDiscountText: "Giảm 1.062.000đ",
    link: "./product-details.html?id=172",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 173,
    name: "Sạc dự phòng Briggs & Stratton P2200",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_23.jpg",
    orginalPrice: "9.500.000đ",
    discountPercent: "-11%",
    currentPrice: "8.455.000đ",
    price: 8455000,
    priceDiscountText: "Giảm 1.045.000đ",
    link: "./product-details.html?id=173",
    quantity: 80,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 174,
    name: "Sạc dự phòng Champion 100263",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_24.jpg",
    orginalPrice: "7.200.000đ",
    discountPercent: "-13%",
    currentPrice: "6.264.000đ",
    price: 6264000,
    priceDiscountText: "Giảm 936.000đ",
    link: "./product-details.html?id=174",
    quantity: 38,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 175,
    name: "Sạc dự phòng DuroMax XP12000EH",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_25.jpg",
    orginalPrice: "15.800.000đ",
    discountPercent: "-7%",
    currentPrice: "14.694.000đ",
    price: 14694000,
    priceDiscountText: "Giảm 1.106.000đ",
    link: "./product-details.html?id=175",
    quantity: 72,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 176,
    name: "Sạc dự phòng WEN 56200i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_26.jpg",
    orginalPrice: "6.500.000đ",
    discountPercent: "-15%",
    currentPrice: "5.525.000đ",
    price: 5525000,
    priceDiscountText: "Giảm 975.000đ",
    link: "./product-details.html?id=176",
    quantity: 73,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 177,
    name: "Sạc dự phòng Firman P03601",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_27.jpg",
    orginalPrice: "5.800.000đ",
    discountPercent: "-17%",
    currentPrice: "4.814.000đ",
    price: 4814000,
    priceDiscountText: "Giảm 986.000đ",
    link: "./product-details.html?id=177",
    quantity: 22,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 178,
    name: "Sạc dự phòng Pulsar PG10000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_28.jpg",
    orginalPrice: "4.200.000đ",
    discountPercent: "-19%",
    currentPrice: "3.402.000đ",
    price: 3402000,
    priceDiscountText: "Giảm 798.000đ",
    link: "./product-details.html?id=178",
    quantity: 49,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 179,
    name: "Sạc dự phòng All Power APGG3000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_29.jpg",
    orginalPrice: "3.800.000đ",
    discountPercent: "-20%",
    currentPrice: "3.040.000đ",
    price: 3040000,
    priceDiscountText: "Giảm 760.000đ",
    link: "./product-details.html?id=179",
    quantity: 46,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 180,
    name: "Sạc dự phòng Sportsman GEN2000i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_30.jpg",
    orginalPrice: "4.500.000đ",
    discountPercent: "-18%",
    currentPrice: "3.690.000đ",
    price: 3690000,
    priceDiscountText: "Giảm 810.000đ",
    link: "./product-details.html?id=180",
    quantity: 5,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 181,
    name: "Sạc dự phòng PowerSmart PS50A",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_31.jpg",
    orginalPrice: "2.900.000đ",
    discountPercent: "-22%",
    currentPrice: "2.262.000đ",
    price: 2262000,
    priceDiscountText: "Giảm 638.000đ",
    link: "./product-details.html?id=181",
    quantity: 73,
    lowStockThreshold: 10,
    brand: "Logitech",
    status: "Active",
  },
  {
    id: 182,
    name: "Sạc dự phòng A-iPower SUA2000i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_32.jpg",
    orginalPrice: "3.200.000đ",
    discountPercent: "-21%",
    currentPrice: "2.528.000đ",
    price: 2528000,
    priceDiscountText: "Giảm 672.000đ",
    link: "./product-details.html?id=182",
    quantity: 64,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 183,
    name: "Sạc dự phòng Westingh WH2200iXLT",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_33.webp",
    orginalPrice: "4.800.000đ",
    discountPercent: "-16%",
    currentPrice: "4.032.000đ",
    price: 4032000,
    priceDiscountText: "Giảm 768.000đ",
    link: "./product-details.html?id=183",
    quantity: 8,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 184,
    name: "Sạc dự phòng Generac GP8000E",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_34.png",
    orginalPrice: "18.500.000đ",
    discountPercent: "-6%",
    currentPrice: "17.390.000đ",
    price: 17390000,
    priceDiscountText: "Giảm 1.110.000đ",
    link: "./product-details.html?id=184",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 185,
    name: "Sạc dự phòng Champion 100302",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_35.png",
    orginalPrice: "12.800.000đ",
    discountPercent: "-8%",
    currentPrice: "11.776.000đ",
    price: 11776000,
    priceDiscountText: "Giảm 1.024.000đ",
    link: "./product-details.html?id=185",
    quantity: 26,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 186,
    name: "Sạc dự phòng DuroMax XP12000E",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_36.webp",
    orginalPrice: "14.200.000đ",
    discountPercent: "-7%",
    currentPrice: "13.206.000đ",
    price: 13206000,
    priceDiscountText: "Giảm 994.000đ",
    link: "./product-details.html?id=186",
    quantity: 26,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 187,
    name: "Sạc dự phòng WEN DF1100T",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_37.png",
    orginalPrice: "8.500.000đ",
    discountPercent: "-12%",
    currentPrice: "7.480.000đ",
    price: 7480000,
    priceDiscountText: "Giảm 1.020.000đ",
    link: "./product-details.html?id=187",
    quantity: 4,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 188,
    name: "Sạc dự phòng Firman P03603",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_38.webp",
    orginalPrice: "7.800.000đ",
    discountPercent: "-14%",
    currentPrice: "6.708.000đ",
    price: 6708000,
    priceDiscountText: "Giảm 1.092.000đ",
    link: "./product-details.html?id=188",
    quantity: 39,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 189,
    name: "Sạc dự phòng Pulsar PG12000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_39.webp",
    orginalPrice: "6.200.000đ",
    discountPercent: "-16%",
    currentPrice: "5.208.000đ",
    price: 5208000,
    priceDiscountText: "Giảm 992.000đ",
    link: "./product-details.html?id=189",
    quantity: 36,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 190,
    name: "Sạc dự phòng All Power APGG5000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_40.webp",
    orginalPrice: "5.500.000đ",
    discountPercent: "-18%",
    currentPrice: "4.510.000đ",
    price: 4510000,
    priceDiscountText: "Giảm 990.000đ",
    link: "./product-details.html?id=190",
    quantity: 29,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 191,
    name: "Sạc dự phòng Sportsman GEN4000i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/FONENG-PX102-Product-1.webp",
    orginalPrice: "6.800.000đ",
    discountPercent: "-15%",
    currentPrice: "5.780.000đ",
    price: 5780000,
    priceDiscountText: "Giảm 1.020.000đ",
    link: "./product-details.html?id=191",
    quantity: 80,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 192,
    name: "Sạc dự phòng PowerSmart PS100A",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_42.png",
    orginalPrice: "4.200.000đ",
    discountPercent: "-20%",
    currentPrice: "3.360.000đ",
    price: 3360000,
    priceDiscountText: "Giảm 840.000đ",
    link: "./product-details.html?id=192",
    quantity: 11,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 193,
    name: "Sạc dự phòng A-iPower SUA4000i",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_43.png",
    orginalPrice: "5.200.000đ",
    discountPercent: "-17%",
    currentPrice: "4.316.000đ",
    price: 4316000,
    priceDiscountText: "Giảm 884.000đ",
    link: "./product-details.html?id=193",
    quantity: 12,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 194,
    name: "Sạc dự phòng Westing WH4500iXLT",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_44.png",
    orginalPrice: "7.500.000đ",
    discountPercent: "-13%",
    currentPrice: "6.525.000đ",
    price: 6525000,
    priceDiscountText: "Giảm 975.000đ",
    link: "./product-details.html?id=194",
    quantity: 46,
    lowStockThreshold: 10,
    brand: "Sony",
    status: "Active",
  },
  {
    id: 195,
    name: "Sạc dự phòng Generac GP15000E",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_45.webp",
    orginalPrice: "25.000.000đ",
    discountPercent: "-5%",
    currentPrice: "23.750.000đ",
    price: 23750000,
    priceDiscountText: "Giảm 1.250.000đ",
    link: "./product-details.html?id=195",
    quantity: 45,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 196,
    name: "Sạc dự phòng Champion 100302",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_46.png",
    orginalPrice: "18.800.000đ",
    discountPercent: "-7%",
    currentPrice: "17.484.000đ",
    price: 17484000,
    priceDiscountText: "Giảm 1.316.000đ",
    link: "./product-details.html?id=196",
    quantity: 42,
    lowStockThreshold: 10,
    brand: "Razer",
    status: "Active",
  },
  {
    id: 197,
    name: "Sạc dự phòng DuroMax XP15000E",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_47.webp",
    orginalPrice: "22.500.000đ",
    discountPercent: "-6%",
    currentPrice: "21.150.000đ",
    price: 21150000,
    priceDiscountText: "Giảm 1.350.000đ",
    link: "./product-details.html?id=197",
    quantity: 55,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
  {
    id: 198,
    name: "Sạc dự phòng WEN DF2200T",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_48.webp",
    orginalPrice: "12.500.000đ",
    discountPercent: "-10%",
    currentPrice: "11.250.000đ",
    price: 11250000,
    priceDiscountText: "Giảm 1.250.000đ",
    link: "./product-details.html?id=198",
    quantity: 18,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 199,
    name: "Sạc dự phòng Firman P03605",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_49.png",
    orginalPrice: "11.200.000đ",
    discountPercent: "-12%",
    currentPrice: "9.856.000đ",
    price: 9856000,
    priceDiscountText: "Giảm 1.344.000đ",
    link: "./product-details.html?id=199",
    quantity: 30,
    lowStockThreshold: 10,
    brand: "SteelSeries",
    status: "Active",
  },
  {
    id: 200,
    name: "Sạc dự phòng Pulsar PG20000",
    category: "powerbank",
    imgSrc: "./assets/img/SACDUPHONG/sacduphong_50.webp",
    orginalPrice: "9.800.000đ",
    discountPercent: "-14%",
    currentPrice: "8.428.000đ",
    price: 8428000,
    priceDiscountText: "Giảm 1.372.000đ",
    link: "./product-details.html?id=200",
    quantity: 12,
    lowStockThreshold: 10,
    brand: "Apple",
    status: "Active",
  },
];
